### PR TITLE
Update checksum

### PR DESCRIPTION
**Pull request by rlguarino**

### CODE REVIEW

**Comment by gpoul** [comment]
I’m currently traveling until mid February and I can certainly merge this, but can’t push it to choco :-(

**Comment by rlguarino** [comment]
I've managed to get the package installed by using my local copy of the package so I'm not blocked anymore. I don't know how people normally do CI/CD for these project but it might be worth looking into.

**Comment by gpoul** [comment]
Noted. And I’ll follow up on it when I get back and hopefully be able to set that up.

**Comment by gpoul** [comment]
Merged commit into master

**Comment by gpoul** [comment]
Pushed to choco as https://chocolatey.org/packages/gcloudsdk/0.0.0.20171229

**Pull request closed without merging**
